# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true

search:
  # remove format to deny access, use lower case.
  # formats: [html, csv, json, rss]
  formats:
    - html
    - json

server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: 'REPLACE_WITH_OUTPUT_OF: openssl rand -hex 32'
  limiter: false # can be disabled for a private instance
  image_proxy: true
  suspended_times:
    SearxEngineTooManyRequests: 60    # reduced from 3600s (1hr) to 60s for agent use
    SearxEngineCaptcha: 120           # reduced from default for private instance
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
